Programm: Assigment2b.o Calculator.o
	g++ Assigment2b.o Calculator.o -o Programm
Assigment2b.o: Assigment2b.cpp
	g++ -c Assigment2b.cpp
Calculator.o: Calculator.cpp
	g++ -c Calculator.cpp
clean:
	rm -f Programm *.o
