MyProg: Assigmen2a.o Readfuncz.o reversbuffer.o
	g++ Assigmen2a.o Readfuncz.o reversbuffer.o -o MyProg
Assigmen2a.o:  Assigmen2a.cpp
	g++ -c Assigmen2a.cpp
Readfuncz.o:  Readfuncz.cpp
	g++ -c Readfuncz.cpp
reversbuffer.o: reversbuffer.cpp
	g++ -c reversbuffer.cpp 
clean:
	rm -f MyProg *.o
